<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AcuLume.Cli</RootNamespace>
    <AssemblyName>aculume</AssemblyName>
    <ApplicationIcon>..\..\assets\aculume.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AcuLume.Core\AcuLume.Core.csproj" />
  </ItemGroup>

</Project>
